repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml           # Проверяет синтаксис YAML файлов
      - id: end-of-file-fixer    # Убеждается, что файлы заканчиваются пустой строкой
      - id: trailing-whitespace  # Удаляет лишние пробелы в конце строк
        exclude: '\.md$'
      - id: check-added-large-files # Предотвращает коммит больших файлов (например, .env или БД)
      - id: detect-private-key
      - id: no-commit-to-branch

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      # Запускаем как линтер
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Автоматически исправляет что может
        types: [python]
      # Запускаем для форматирования импортов
      - id: ruff-format
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [., --config-file=pyproject.toml]
        pass_filenames: false
        additional_dependencies: [
          "pydantic==2.10.4",
          "fastapi==0.135.1",
          "jinja2==3.1.6",
          "bleach==6.3.0",
          "types-bleach==6.3.0.20251115",
          "filetype==1.0.7",
        ]

  - repo: https://github.com/pypa/pip-audit
    rev: v2.10.0
    hooks:
      -   id: pip-audit
          args: ["-r", "requirements.txt"]

ci:
  # Leave pip-audit to only run locally and not in CI
  # pre-commit.ci does not allow network calls
  skip: [pip-audit]
